# Generated by Django 4.0.5 on 2022-06-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
